In [4]:
import pandas as pd

# Load dataset
df = pd.read_csv("sales_large.csv")

# Compute total sales for each product in each region
total_sales = df.groupby(["Region", "Product"])["Sales"].sum().reset_index()

# Identify the product with the highest total sales
top_product = df.groupby("Product")["Sales"].sum().idxmax()

print(total_sales)
print("Top Product:", top_product)

     Region  Product  Sales
0   Central   Apples   9000
1   Central  Oranges   8000
2      East   Apples   5000
3      East  Bananas   8500
4      East  Oranges  13900
5     North   Apples   7200
6     North  Bananas   9000
7     North  Oranges   4900
8     South   Apples  12900
9     South  Bananas   5100
10    South  Oranges   3000
11     West   Apples  18900
12     West  Bananas  14700
13     West  Oranges   7500
Top Product: Apples